
prose:
  metadata:
    "/": |
      title:    "Title of your page"
      abstract: "Abstract"
    "/services": |
      title:    "Title of your page"
      abstract: "Abstract"
    "_posts/projects": |
      name: "Project Name"
      img:  "Project Thumbnail"